-- An unambiguous order for a conversation.
--
-- The question and the answer are written in one request, so both rows landed
-- on the same created_at down to the microsecond. Ordering by time then put
-- them in an arbitrary order, and the coach was handed a question with its
-- answer stripped off — after which he correctly reported having no memory of
-- a conversation he had just had.
--
-- A counter cannot tie with itself.
alter table public.coach_messages
    add column seq bigint generated by default as identity;

create index coach_messages_user_seq on public.coach_messages (user_id, seq);
